---
title: "R Markdown Parameterization - GUI"
author: "CCHMC RUG"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: journal
    highlight: breezedark
    toc: TRUE
    toc_float: TRUE
    code_folding: hide
params:
  year_range:
    label: "Year Range"
    input: slider
    min: 1980
    max: 2019
    step: 1
    round: 1
    sep: ''
    value:
      - 2019
      - 2019
  temp:
    label: "Temperature"
    value: TRUE
  max_temp:
    label: "Max Temperature"
    value: TRUE
  min_temp: 
    label: "Minimum Temperature"
    value: TRUE
  precip:
    label: "Precipitation"
    value: TRUE
  cumulative_precip:
    label: "Cumulative Precipitation"
    value: TRUE
---

***To knit this .Rmd file with parameters using the GUI, click the down arrow next to the 'Knit' button and select "Knit with Parameters...".***

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, comment = NA)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

```

```{r lib, echo = FALSE, warning = FALSE, message = FALSE}

library(tidyverse)

```

```{r import, echo = FALSE, warning = FALSE, message = FALSE}
d_weather <- read_rds("./rug_weather/cincy_weather.rds")
```

```{r yr_range, echo = FALSE}

## This chunk takes the minimum and maximum value of the year range and generates a numeric vetor of years 
## to subset the data

param_range <- params$year_range
y1 = param_range[1]
y2 = param_range[2]

y_range <- y1:y2

```

```{r medians, echo = FALSE}

## This chunk filters the weather data to the range of years and calculates the median daily 
## temperature by year 

d <- d_weather %>% 
  filter(YEAR %in% y_range)

#d <- d_weather %>% filter(YEAR %in% c(2016, 2018, 2019))

weather_medians <- d %>% 
  group_by(YEAR) %>% 
  summarise(med_temp = median(TEMP),
            med_max_temp = median(MAX),
            med_min_temp = median(MIN))

```

## Daily Temperature

```{r temp, eval = params$temp}

ggplot(d) +
  geom_col(aes(YDAY, TEMP, color = TEMP)) +
  scale_color_viridis_c() +
  geom_hline(aes(yintercept = med_temp), data = weather_medians, color = "red") +
  facet_wrap(~YEAR) +
  ylab("Temperature (C)") +
  xlab("Day of Year") +
  labs(color = "Temperature")

```

```{r temp_message, echo = FALSE}
if (params$temp == FALSE) {
  print("Please set this parameter to 'TRUE' to plot data.")
}
```

## Maximum Temperature

```{r max_temp, eval = params$max_temp}

ggplot(d) +
  geom_col(aes(YDAY, MAX, color = MAX)) +
  scale_color_viridis_c() +
  geom_hline(aes(yintercept = med_max_temp), data = weather_medians, color = "red") +
  facet_wrap(~YEAR) +
  ylab("Maximum Temperature (C)") +
  xlab("Day of Year") +
  labs(color = "Max. Temperature")

```

```{r max_message, echo = FALSE}
if (params$max_temp == FALSE) {
  print("Please set this parameter to 'TRUE' to plot data.")
}
```

## Minimum Temperature

```{r min_temp, eval = params$min_temp}

ggplot(d) +
  geom_col(aes(YDAY, MIN, color = MIN)) +
  scale_color_viridis_c() +
  geom_hline(aes(yintercept = med_min_temp), data = weather_medians, color = "red") +
  facet_wrap(~YEAR) +
  ylab("Minimum Temperature (C)") +
  xlab("Day of Year") +
  labs(color = "Min. Temperature")

```

```{r min_message, echo = FALSE}
if (params$min_temp == FALSE) {
  print("Please set this parameter to 'TRUE' to plot data.")
}
```

## Monthly Precipitation

```{r precip, eval = params$precip}

precip <- d %>% 
  group_by(YEAR, MONTH) %>% 
  summarise(total_precip = sum(PRCP))

ggplot(precip) +
  geom_col(aes(MONTH, total_precip, fill = total_precip)) +
  scale_fill_viridis_c() +
  geom_hline(aes(yintercept = median(total_precip)), data = precip, color = "red") +
  facet_wrap(~YEAR) +
  ylab("Precipitation (mm)") +
  xlab("Month") +
  labs(fill = "Precipitation")

```

```{r precip_message, echo = FALSE}
if (params$precip == FALSE) {
  print("Please set this parameter to 'TRUE' to plot data.")
}
```

## Cumulative Precipitation

```{r cumulative_precip, eval = params$cumulative_precip}

cumulative_prcp <- d %>% 
  group_by(YEAR) %>% 
  mutate(cumulative_prcp = cumsum(PRCP))

ggplot(cumulative_prcp) +
  geom_col(aes(YDAY, cumulative_prcp, color = MAX)) +
  scale_color_viridis_c() +
  facet_wrap(~YEAR) +
  ylab("Cumulative Precipitation (mm)") +
  xlab("Day of Year") +
  labs(color = "Precipitation")

```

```{r cumulative_precip_message, echo = FALSE}
if (params$cumulative_precip == FALSE) {
  print("Please set this parameter to 'TRUE' to plot data.")
}
```
